task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 3
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./data/CrowdHumanCityPersons_VHF/images
    ann_file: ./data/CrowdHumanCityPersons_VHF/annotations/instances_train_visiblebody_head_face.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./data/CrowdHumanCityPersons_VHF/images
    ann_file: ./data/CrowdHumanCityPersons_VHF/annotations/instances_val_visiblebody_head_face.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
